### ISSUE TITLE
Confidence Intervals

### ISSUE THREAD

**Issue by alex-bryzghalov** [dermasugita/Viola-SV#71]
Dear developers, firs of all thank you for the great software which potentially makes much easier life of the people working with SVs. Currently I am working with conversion of Manta output VCF into  bedpe format and there is one thing I want to pinpoint is the problem with right estimation of the confidence intervals within to_bedpe_like function. 
Current version of Manta describe CIPOS and CIEND in format where the first value is 0 or negative, like CIPOS=-203,204 or CIEND=-345,346.

So in function:

        if confidence_intervals:
            if 'cipos' in self.table_list and 'ciend' in self.table_list:
                df_svpos = self.append_infos(df_svpos, ['cipos', 'ciend'])
                df_svpos['start1'] = df_svpos['pos1'] - df_svpos['cipos_0'] - 1
                df_svpos['end1'] = df_svpos['pos1'] + df_svpos['cipos_1']
                df_svpos['start2'] = df_svpos['pos2'] - df_svpos['ciend_0'] - 1
                df_svpos['end2'] = df_svpos['pos2'] + df_svpos['ciend_1']
            else:
                pass # raise some exception

We need to change to:

        if confidence_intervals:
            if 'cipos' in self.table_list and 'ciend' in self.table_list:
                df_svpos = self.append_infos(df_svpos, ['cipos', 'ciend'])
                df_svpos['start1'] = df_svpos['pos1'] + df_svpos['cipos_0'] - 1
                df_svpos['end1'] = df_svpos['pos1'] + df_svpos['cipos_1']
                df_svpos['start2'] = df_svpos['pos2'] + df_svpos['ciend_0'] - 1
                df_svpos['end2'] = df_svpos['pos2'] + df_svpos['ciend_1']
            else:
                pass # raise some exception

because of the extraction of the negative value will led to the sum. Other way is to use modulus.
I've checked the vcf specification and according to them cipos_0  and ciend_0 will always be 0 or negative.
Hope it will help to improve your beautiful software

**Comment by dermasugita** [comment]
Thank you for reporting this! We'll fix it as soon as possible.

**Comment by dermasugita** [comment]
This problem has been fixed since version 1.0.0.dev7.

Thank you for your great contribution! If you have any questions or requests, feel free to contact us.
