### ISSUE TITLE
SVLEN missing for some SV types and callers

### ISSUE THREAD

**Issue by arnikz** [dermasugita/Viola-SV#72]
Hi,

Thanks for developing this library/command-line tool. I'm thinking of including it in the next release of the [sv-callers](https://github.com/GooglingTheCancerGenome/sv-callers) workflow. I would appreciate your help with correcting the VCF/INFO output (i.e., processed by `breakend2breakpoint()` and `to_vcf(...)`):

- Manta 
  - DEL: SVLEN < 0 
  - DUP & INV: SVLEN > 0
  - TRA: SVLEN=0 missing ❌ 

- Delly ✔️ 
  - DEL: SVLEN<0
  - DUP & INV: SVLEN>0
  - TRA: SVLEN=0

- Lumpy
  - DEL: SVLEN<0
  - DUP: SVLEN>0
  - INV: SVLEN>0 missing ❌ 
  - TRA: SVLEN=0 missing ❌ 
 
- GRIDSS ❌ 
  - SVLEN missing for all SVTYPEs

**Comment by dermasugita** [comment]
Thanks for your feedback. I'm now working on this problem. Please wait for some time.

**Comment by arnikz** [comment]
Hi, could you share your approx. timeline? Thanks.

**Comment by dermasugita** [comment]
An update will be made during April. Thanks!

**Comment by dermasugita** [comment]
Hi,
We've now released a new version! Please check it out.

**Comment by arnikz** [comment]
Excellent! Thanks.

**Comment by arnikz** [comment]
I can find the new release in [pypi](https://pypi.org/project/Viola-SV/) but not in [here](https://github.com/dermasugita/Viola-SV/releases). Could you please add? Thanks.

**Comment by dermasugita** [comment]
Sorry, I've just created it.

**Comment by arnikz** [comment]
Hi,
Just to let you known that I incorporated your package in the latest release of the [sv-callers](https://github.com/GooglingTheCancerGenome/sv-callers/releases/tag/v1.2.0) workflow. Thanks again for your help.

**Comment by dermasugita** [comment]
Hi!
Thank you for integrating our software!
Please let us know if there are any more problems.
