### ISSUE TITLE
Error on vcf.classify_manual_svtype()

### ISSUE THREAD

**Issue by byemypast** [dermasugita/Viola-SV#73]
Hi dermasugita,
Thanks for creating such a important tool of sv analysis.
I have a problem on vcf.classify_manual_svtype(). When I try to get sv signature on my custom data, I encounter this error.

` myvcf
INFO=ciend,cipos,chr2,pos2,end,pe,mapq,srmapq,sr,srq,consensus,ce,ct,svlen,imprecise,precise,svtype,svmethod,inslen,homlen,rdratio,somatic
Documentation of Vcf object ==> https://dermasugita.github.io/ViolaDocs/docs/html/reference/vcf.html
            id             be1             be2 strand  qual svtype
0  DEL00001014   chr4:49110411   chr4:49146567     +-    26    DEL
1  INV00001181   chr4:49121125   chr4:49637332     --    25    INV
2  DEL00001383   chr4:49155708   chr4:49156446     +-    25    DEL
3  INV00001388   chr4:49156451   chr4:49659566     --    36    INV
4  BND00003844  chr15:28336694   chr9:68426350     +-    30    BND
5  BND00005068  chr21:10703711  chr16:33976169     +-   109    BND
6  DUP00005081  chr21:10721501  chr21:10723278     -+    59    DUP
7  DUP00005091  chr21:10761984  chr21:10762727     -+    69    DUP

myvcf.classify_manual_svtype(definitions='./resources/definitions/sv_class_article.txt')

Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "C:\Python39\lib\site-packages\viola\core\vcf.py", line 979, in classify_manual_svtype
    ls_conditions, ls_names = self._parse_signature_definition_file(open(definitions, 'r'))
  File "C:\Python39\lib\site-packages\viola\core\bedpe.py", line 864, in _parse_signature_definition_file
    result = self.filter(ls_query, query_logic=query_logic).ids
  File "C:\Python39\lib\site-packages\viola\core\vcf.py", line 757, in filter
    set_result = eval(expr)
  File "<string>", line 1, in <module>
TypeError: unsupported operand type(s) for |: 'NoneType' and 'NoneType'
>>>`

Could you kindly suggest what should I do to resolve this problem?
Thanks!

**Comment by byemypast** [comment]
vcf data import from delly-filter result btw

**Comment by dermasugita** [comment]
Thanks for your feedback. Please modify the svtype filters in the definition file (sv_class_article.txt). This error may be caused by the difference in the naming convention of SV types between PCAWG and Delly. For example, "inversion" is represented as "t2tINV" and "h2hINV" in PCAWG data while "INV" is used in Delly output. "TRA" vs "BND" is another difference. 

Anyway, we're going to enhance Viola to raise appropriate error messages in these situations. Thanks!

**Comment by byemypast** [comment]
Great thanks for your advanced suggestion.
Have a nice day!
